# logging_config.yaml (파일 로깅 추가 및 경로 수정 버전)
version: 1
disable_existing_loggers: False # 기존 로거 설정을 유지하려면 False

formatters:
  default:
    # format 문자열에 trace_id, comic_id 포함 (기본값 N/A)
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(trace_id)s] [%(comic_id)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    defaults:
      trace_id: "N/A"
      comic_id: "N/A"
  detailed: # 파일용 상세 포매터
    format: "[%(asctime)s] [%(levelname)s] [%(name)s:%(lineno)d] [%(threadName)s] [%(trace_id)s] [%(comic_id)s] - %(message)s"
    datefmt: '%Y-%m-%d %H:%M:%S'
    defaults:
      trace_id: "N/A"
      comic_id: "N/A"
  simple: # 필요시 간단 포매터
    format: "%(levelname)s - %(name)s - [%(trace_id)s] [%(comic_id)s] - %(message)s"
    defaults:
      trace_id: "N/A"
      comic_id: "N/A"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO  # --- 콘솔 레벨은 INFO로 유지 (기존 DEBUG에서 변경) ---
    formatter: default # default 포매터 사용
    stream: ext://sys.stdout

  file_handler: # --- 파일 핸들러 정의 ---
    class: logging.handlers.RotatingFileHandler # 자동 교체 핸들러
    level: DEBUG  # --- 파일에는 DEBUG 레벨 이상 모두 기록 ---
    formatter: detailed # 자세한 포매터 사용
    filename: app/log/app_workflow.log # --- 로그 파일 경로 및 이름 지정 ---
    maxBytes: 10485760 # 예: 10MB
    backupCount: 5     # 예: 백업 파일 5개 유지
    encoding: utf8     # UTF-8 인코딩

loggers:
  # --- 특정 로거 레벨 조정 (선택 사항) ---
  # newsum: # 앱 특정 로거 (사용 시)
  #   level: DEBUG
  #   handlers: [console, file_handler]
  #   propagate: no # 루트로 전파 안함
  httpx:
    level: WARNING # httpx 로그 줄이기
    handlers: [console, file_handler] # 파일에도 기록 (선택적)
    propagate: no
  aiohttp:
    level: WARNING
    handlers: [console, file_handler]
    propagate: no
  prawcore:
    level: WARNING
    handlers: [console, file_handler]
    propagate: no
  tweepy:
    level: WARNING
    handlers: [console, file_handler]
    propagate: no
  # 다른 라이브러리 로거 추가 가능 (예: boto3, botocore)
  boto3:
    level: INFO # AWS SDK 로그 레벨 조정
    handlers: [console, file_handler]
    propagate: no
  botocore:
    level: INFO
    handlers: [console, file_handler]
    propagate: no
  urllib3:
    level: INFO
    handlers: [console, file_handler]
    propagate: no

root: # 기본 루트 로거 설정
  level: DEBUG # --- 루트 로거 레벨 DEBUG로 설정 (파일 핸들러가 DEBUG 처리 가능하도록) ---
  handlers: [console, file_handler] # --- 콘솔과 파일 핸들러 모두 사용 ---