# logging_config.yaml
version: 1
disable_existing_loggers: false

formatters:
  default:
    # format 문자열에 %(trace_id)s 와 %(comic_id)s 추가
    # '-'는 extra 에 해당 값이 없을 경우 기본값으로 표시될 문자열
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] [%(trace_id)s] [%(comic_id)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    # 기본값 설정 (Python 3.10 이상)
    defaults:
      trace_id: "N/A"
      comic_id: "N/A"
  simple:
    format: "%(levelname)s - %(name)s - [%(trace_id)s] [%(comic_id)s] - %(message)s"
    defaults:
      trace_id: "N/A"
      comic_id: "N/A"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default # trace_id 등을 포함한 default 포매터 사용
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: default # trace_id 등을 포함한 default 포매터 사용
    filename: app.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

loggers:
  newsom:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  # httpx 로거 레벨 조정 (필요 시)
  httpx:
    level: WARNING # httpx의 INFO 레벨 로그가 너무 많을 경우 WARNING으로 조정
    handlers: [console]
    propagate: no
  # 다른 라이브러리 로거 레벨 조정 (예: aiohttp, praw, tweepy)
  aiohttp:
    level: WARNING
  prawcore: # praw의 저수준 로거
    level: WARNING
  tweepy:
    level: WARNING

root:
  level: INFO
  handlers: [console] # 루트 로거는 기본적으로 콘솔만 사용하도록 변경 (선택 사항)